### ISSUE TITLE
Invalid URL call

### ISSUE THREAD

**Issue by djKooks** [appcues/mojito#48]
Hello,
I was using `Mint` library for test, and trying to move on here because it seems more simple to use. Thanks for your work.

This is my `Mint` code:
```
{:ok, conn} = Mint.HTTP.connect(:http, "localhost", 8080)
    {:ok, conn, request_ref} =
      Mint.HTTP.request(conn, "GET", "/v1/api/user/001", [
        {"content-type", "application/json"}
      ], "")

    # read and parse the response
    receive do
      message ->
        {:ok, conn, responses} = Mint.HTTP.stream(conn, message)
```

this was working well, but:
```
api_endpoint = "http://localhost:8080/v1/api/user/001"

case Mojito.request(:get, url: api_endpoint) do
  {:ok, response} -> Logger.info "Okay: #{response}"
  {:error, reason} -> IO.puts(reason)
end
```
this returns:
```
** (Protocol.UndefinedError) protocol String.Chars not implemented for %Mojito.Error{message: "invalid URL", reason: %FunctionClauseError{args: nil, arity: 1, clauses: nil, function: :parse, kind: nil, module: URI}} of type Mojito.Error (a struct)
    (elixir) lib/string/chars.ex:3: String.Chars.impl_for!/1
    (elixir) lib/string/chars.ex:22: String.Chars.to_string/1
    (elixir) lib/io.ex:654: IO.puts/2
    (mix) lib/mix/task.ex:331: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:79: Mix.CLI.run_task/2
```

Could you give me a guide if I'm doing something wrong?

Thanks.

**Comment by gamache** [comment]
Hi djKooks! Thanks for writing.

The issue here is that you're trying to print a struct (`%Mojito.Error{}`) as though it were a string, and there's no standard way to do that. If you change your `IO.puts(reason)` to `IO.puts(inspect(reason))`, the error will go away. Hope this helps!

**Comment by djKooks** [comment]
@gamache what a dumb question I've did...sorry...I'm starter in Elixir.

Thanks for your guide~
